# Generated by scripts/generate_resource_types.py from Microsoft's published abbreviations and
# naming rules. Regenerating overwrites this file, so to change a rule or add a type for good, use
# the custom_resource_types input instead of editing here.
#
# code: abbreviation used in the name. min_length, max_length: characters allowed.
# lowercase, hyphens, starts_with_letter: naming rules. scope: where the name must be unique.
# verified: false when Microsoft publishes no rule, so the defaults are used.
locals {
  builtin_resource_types = {
    ai_search                                  = { code = "srch", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    ai_video_indexer                           = { code = "avi", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    aks_cluster                                = { code = "aks", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    aks_fleet_manager                          = { code = "fleet", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    aks_system_node_pool                       = { code = "npsystem", min_length = 1, max_length = 12, lowercase = true, hyphens = false, starts_with_letter = true, scope = "managed cluster", verified = true }
    aks_system_node_pool_linux                 = { code = "npsystem", min_length = 1, max_length = 12, lowercase = true, hyphens = false, starts_with_letter = true, scope = "managed cluster", verified = true }
    aks_system_node_pool_windows               = { code = "npsystem", min_length = 1, max_length = 6, lowercase = true, hyphens = false, starts_with_letter = true, scope = "managed cluster", verified = true }
    aks_user_node_pool                         = { code = "np", min_length = 1, max_length = 12, lowercase = true, hyphens = false, starts_with_letter = true, scope = "managed cluster", verified = true }
    aks_user_node_pool_linux                   = { code = "np", min_length = 1, max_length = 12, lowercase = true, hyphens = false, starts_with_letter = true, scope = "managed cluster", verified = true }
    aks_user_node_pool_windows                 = { code = "np", min_length = 1, max_length = 6, lowercase = true, hyphens = false, starts_with_letter = true, scope = "managed cluster", verified = true }
    analysis_services_server                   = { code = "as", min_length = 3, max_length = 63, lowercase = true, hyphens = false, starts_with_letter = true, scope = "resource group", verified = true }
    api_management_service_instance            = { code = "apim", min_length = 1, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = true, scope = "global", verified = true }
    app_configuration_store                    = { code = "appcs", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    app_service_environment                    = { code = "ase", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    app_service_plan                           = { code = "asp", min_length = 1, max_length = 60, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    application_gateway                        = { code = "agw", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    application_insights                       = { code = "appi", min_length = 1, max_length = 260, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    application_security_group                 = { code = "asg", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    arc_enabled_kubernetes_cluster             = { code = "arck", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    arc_enabled_server                         = { code = "arcs", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    arc_gateway                                = { code = "arcgw", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    arc_private_link_scope                     = { code = "pls", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    automation_account                         = { code = "aa", min_length = 6, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = true, scope = "resource group & region <br>(See note below)", verified = true }
    availability_set                           = { code = "avail", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    backup_resource_guard                      = { code = "rgd", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    backup_vault                               = { code = "bvault", min_length = 2, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = true, scope = "resource group", verified = true }
    backup_vault_policy                        = { code = "bkpol", min_length = 1, max_length = 75, lowercase = false, hyphens = true, starts_with_letter = false, scope = "backup vault", verified = true }
    bastion                                    = { code = "bas", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    batch_accounts                             = { code = "ba", min_length = 3, max_length = 24, lowercase = true, hyphens = false, starts_with_letter = false, scope = "Region", verified = true }
    bot_service                                = { code = "bot", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    cdn_endpoint                               = { code = "cdne", min_length = 1, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    cdn_profile                                = { code = "cdnp", min_length = 1, max_length = 260, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    cloud_service                              = { code = "cld", min_length = 1, max_length = 15, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    communication_services                     = { code = "acs", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    computer_vision                            = { code = "cv", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    connections                                = { code = "con", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    container_apps                             = { code = "ca", min_length = 2, max_length = 32, lowercase = true, hyphens = true, starts_with_letter = true, scope = "resource group", verified = true }
    container_apps_environment                 = { code = "cae", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    container_apps_job                         = { code = "caj", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    container_instance                         = { code = "ci", min_length = 1, max_length = 63, lowercase = true, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    container_registry                         = { code = "cr", min_length = 5, max_length = 50, lowercase = false, hyphens = false, starts_with_letter = false, scope = "global", verified = true }
    content_moderator                          = { code = "cm", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    content_safety                             = { code = "cs", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    cosmos_db_database                         = { code = "cosmos", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    cosmos_db_for_apache_cassandra_account     = { code = "coscas", min_length = 3, max_length = 44, lowercase = true, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    cosmos_db_for_apache_gremlin_account       = { code = "cosgrm", min_length = 3, max_length = 44, lowercase = true, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    cosmos_db_for_mongodb_account              = { code = "cosmon", min_length = 3, max_length = 44, lowercase = true, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    cosmos_db_for_nosql_account                = { code = "cosno", min_length = 3, max_length = 44, lowercase = true, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    cosmos_db_for_table_account                = { code = "costab", min_length = 3, max_length = 44, lowercase = true, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    cosmos_db_postgresql_cluster               = { code = "cospos", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    custom_vision_prediction                   = { code = "cstv", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    custom_vision_training                     = { code = "cstvt", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    data_collection_endpoint                   = { code = "dce", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    data_explorer_cluster                      = { code = "dec", min_length = 4, max_length = 22, lowercase = true, hyphens = false, starts_with_letter = true, scope = "global", verified = true }
    data_explorer_cluster_database             = { code = "dedb", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    data_factory                               = { code = "adf", min_length = 3, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    data_lake_store_account                    = { code = "dls", min_length = 3, max_length = 24, lowercase = true, hyphens = false, starts_with_letter = false, scope = "global", verified = true }
    database_migration_service_instance        = { code = "dms", min_length = 2, max_length = 62, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    databricks_access_connector                = { code = "dbac", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    databricks_workspace                       = { code = "dbw", min_length = 3, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    deployment_scripts                         = { code = "script", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    digital_twin_instance                      = { code = "dt", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    disk_encryption_set                        = { code = "des", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    dns_forwarding_ruleset                     = { code = "dnsfrs", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    dns_private_resolver                       = { code = "dnspr", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    dns_private_resolver_inbound_endpoint      = { code = "in", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    dns_private_resolver_outbound_endpoint     = { code = "out", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    document_intelligence                      = { code = "di", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    enclave_community                          = { code = "cmt", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    enclave_community_endpoint                 = { code = "ce", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    enclave_dedicated_hub                      = { code = "dh", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    enclave_enclave                            = { code = "ve", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    enclave_enclave_connections                = { code = "ec", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    enclave_enclave_endpoints                  = { code = "ee", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    enclave_transit_hubs                       = { code = "th", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    enclave_workloads                          = { code = "wl", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    event_grid_domain                          = { code = "evgd", min_length = 3, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    event_grid_namespace                       = { code = "evgns", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    event_grid_subscriptions                   = { code = "evgs", min_length = 3, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    event_grid_system_topic                    = { code = "egst", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    event_grid_topic                           = { code = "evgt", min_length = 3, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = false, scope = "domain", verified = true }
    event_hub                                  = { code = "evh", min_length = 1, max_length = 256, lowercase = false, hyphens = true, starts_with_letter = false, scope = "namespace", verified = true }
    event_hub_consumer_group                   = { code = "evhcg", min_length = 1, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = false, scope = "event hub", verified = true }
    event_hubs_namespace                       = { code = "evhns", min_length = 6, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = true, scope = "global", verified = true }
    expressroute_circuit                       = { code = "erc", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    expressroute_direct                        = { code = "erd", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    expressroute_gateway                       = { code = "ergw", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    fabric_capacity                            = { code = "fc", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    face_api                                   = { code = "face", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    file_share                                 = { code = "share", min_length = 3, max_length = 63, lowercase = true, hyphens = true, starts_with_letter = false, scope = "storage account", verified = true }
    firewall                                   = { code = "afw", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    firewall_policy                            = { code = "afwp", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    foundry_account                            = { code = "aif", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    foundry_account_project                    = { code = "proj", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    foundry_hub                                = { code = "hub", min_length = 3, max_length = 33, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    foundry_hub_project                        = { code = "proj", min_length = 3, max_length = 33, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    foundry_tools_multi_service_account        = { code = "ais", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    front_door_classic                         = { code = "afd", min_length = 5, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    front_door_firewall_policy                 = { code = "fdfp", min_length = 1, max_length = 128, lowercase = false, hyphens = false, starts_with_letter = true, scope = "resource group", verified = true }
    front_door_standard_premium_endpoint       = { code = "fde", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    front_door_standard_premium_profile        = { code = "afd", min_length = 1, max_length = 260, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    function_app                               = { code = "func", min_length = 2, max_length = 60, lowercase = false, hyphens = true, starts_with_letter = false, scope = "Global or per domain; see note below.", verified = true }
    gallery                                    = { code = "gal", min_length = 1, max_length = 80, lowercase = false, hyphens = false, starts_with_letter = false, scope = "resource group", verified = true }
    hdinsight_hadoop_cluster                   = { code = "hadoop", min_length = 3, max_length = 59, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    hdinsight_hbase_cluster                    = { code = "hbase", min_length = 3, max_length = 59, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    hdinsight_kafka_cluster                    = { code = "kafka", min_length = 3, max_length = 59, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    hdinsight_ml_services_cluster              = { code = "mls", min_length = 3, max_length = 59, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    hdinsight_spark_cluster                    = { code = "spark", min_length = 3, max_length = 59, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    hdinsight_storm_cluster                    = { code = "storm", min_length = 3, max_length = 59, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    health_insights                            = { code = "hi", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    hosting_environment                        = { code = "host", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    image_template                             = { code = "it", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    immersive_reader                           = { code = "ir", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    integration_account                        = { code = "ia", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    iot_hub                                    = { code = "iot", min_length = 3, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    ip_group                                   = { code = "ipg", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    key_vault                                  = { code = "kv", min_length = 3, max_length = 24, lowercase = false, hyphens = true, starts_with_letter = true, scope = "global", verified = true }
    key_vault_managed_hsm                      = { code = "kvmhsm", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    language_service                           = { code = "lang", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    load_balancer_external                     = { code = "lbe", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    load_balancer_internal                     = { code = "lbi", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    load_balancer_rule                         = { code = "rule", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "load balancer", verified = true }
    load_testing_instance                      = { code = "lt", min_length = 1, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    local_network_gateway                      = { code = "lgw", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    log_analytics_query_packs                  = { code = "pack", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    log_analytics_workspace                    = { code = "log", min_length = 4, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    logic_app                                  = { code = "logic", min_length = 1, max_length = 43, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    machine_learning_workspace                 = { code = "mlw", min_length = 3, max_length = 33, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    managed_devops_pools                       = { code = "mdp", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    managed_disk                               = { code = "osdisk", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    managed_disk_data                          = { code = "disk", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    managed_grafana                            = { code = "amg", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    managed_identity                           = { code = "id", min_length = 3, max_length = 128, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    managed_redis                              = { code = "amr", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    management_group                           = { code = "mg", min_length = 1, max_length = 90, lowercase = false, hyphens = true, starts_with_letter = false, scope = "tenant", verified = true }
    maps_account                               = { code = "map", min_length = 1, max_length = 98, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    migrate_project                            = { code = "migr", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    monitor_action_group                       = { code = "ag", min_length = 1, max_length = 260, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    monitor_alert_processing_rule              = { code = "apr", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    monitor_data_collection_rule               = { code = "dcr", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    mysql_database                             = { code = "mysql", min_length = 3, max_length = 63, lowercase = true, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    nat_gateway                                = { code = "ng", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    network_interface                          = { code = "nic", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    network_security_group                     = { code = "nsg", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    network_security_group_security_rules      = { code = "nsgsr", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "network security group", verified = true }
    network_security_perimeter                 = { code = "nsp", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    network_watcher                            = { code = "nw", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    notification_hubs                          = { code = "ntf", min_length = 1, max_length = 260, lowercase = false, hyphens = true, starts_with_letter = false, scope = "namespace", verified = true }
    notification_hubs_namespace                = { code = "ntfns", min_length = 6, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = true, scope = "global", verified = true }
    openai_service                             = { code = "oai", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    postgresql_flexible_server                 = { code = "pgsql", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    power_bi_embedded                          = { code = "pbi", min_length = 3, max_length = 63, lowercase = true, hyphens = false, starts_with_letter = true, scope = "region", verified = true }
    private_endpoint                           = { code = "pep", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    private_link                               = { code = "pl", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    provisioning_services                      = { code = "provs", min_length = 3, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    provisioning_services_certificate          = { code = "pcert", min_length = 1, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "provisioningServices", verified = true }
    proximity_placement_group                  = { code = "ppg", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    public_ip_address                          = { code = "pip", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    public_ip_address_prefix                   = { code = "ippre", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    purview_instance                           = { code = "pview", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    recovery_services_vault                    = { code = "rsv", min_length = 2, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = true, scope = "resource group", verified = true }
    resource_group                             = { code = "rg", min_length = 1, max_length = 90, lowercase = false, hyphens = true, starts_with_letter = false, scope = "subscription", verified = true }
    restore_point_collection                   = { code = "rpc", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    route_filter                               = { code = "rf", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    route_server                               = { code = "rtserv", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    route_table                                = { code = "rt", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    service_bus_namespace                      = { code = "sbns", min_length = 6, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = true, scope = "global", verified = true }
    service_bus_queue                          = { code = "sbq", min_length = 1, max_length = 260, lowercase = false, hyphens = true, starts_with_letter = false, scope = "namespace", verified = true }
    service_bus_topic                          = { code = "sbt", min_length = 1, max_length = 260, lowercase = false, hyphens = true, starts_with_letter = false, scope = "namespace", verified = true }
    service_bus_topic_subscription             = { code = "sbts", min_length = 1, max_length = 50, lowercase = false, hyphens = true, starts_with_letter = false, scope = "topic", verified = true }
    service_endpoint_policy                    = { code = "se", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    service_fabric_cluster                     = { code = "sf", min_length = 4, max_length = 23, lowercase = true, hyphens = true, starts_with_letter = true, scope = "region", verified = true }
    service_fabric_managed_cluster             = { code = "sfmc", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    signalr                                    = { code = "sigr", min_length = 3, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = true, scope = "global", verified = true }
    snapshot                                   = { code = "snap", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    speech_service                             = { code = "spch", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    sql_database                               = { code = "sqldb", min_length = 1, max_length = 128, lowercase = false, hyphens = true, starts_with_letter = false, scope = "server", verified = true }
    sql_database_server                        = { code = "sql", min_length = 1, max_length = 63, lowercase = true, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    sql_elastic_job_agent                      = { code = "sqlja", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    sql_elastic_pool                           = { code = "sqlep", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    sql_managed_instance                       = { code = "sqlmi", min_length = 1, max_length = 63, lowercase = true, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    ssh_key                                    = { code = "sshkey", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    static_web_app                             = { code = "stapp", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    storage_account                            = { code = "st", min_length = 3, max_length = 24, lowercase = true, hyphens = false, starts_with_letter = false, scope = "global", verified = true }
    storage_sync_service                       = { code = "sss", min_length = 1, max_length = 260, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    stream_analytics                           = { code = "asa", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    synapse_analytics_private_link_hub         = { code = "synplh", min_length = 1, max_length = 45, lowercase = true, hyphens = false, starts_with_letter = false, scope = "resource group", verified = true }
    synapse_analytics_spark_pool               = { code = "synsp", min_length = 1, max_length = 15, lowercase = false, hyphens = false, starts_with_letter = true, scope = "workspace", verified = true }
    synapse_analytics_sql_dedicated_pool       = { code = "syndp", min_length = 1, max_length = 60, lowercase = false, hyphens = false, starts_with_letter = false, scope = "workspace", verified = true }
    synapse_analytics_workspaces               = { code = "synw", min_length = 1, max_length = 50, lowercase = true, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    template_specs                             = { code = "ts", min_length = 1, max_length = 90, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    time_series_insights_environment           = { code = "tsi", min_length = 1, max_length = 90, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    traffic_manager_profile                    = { code = "traf", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "global", verified = true }
    translator                                 = { code = "trsl", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    user_defined_route                         = { code = "udr", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "route table", verified = true }
    virtual_desktop_application_group          = { code = "vdag", min_length = 3, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    virtual_desktop_host_pool                  = { code = "vdpool", min_length = 3, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    virtual_desktop_scaling_plan               = { code = "vdscaling", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    virtual_desktop_workspace                  = { code = "vdws", min_length = 3, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    virtual_machine                            = { code = "vm", min_length = 1, max_length = 15, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    virtual_machine_windows                    = { code = "vm", min_length = 1, max_length = 15, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    virtual_machine_linux                      = { code = "vm", min_length = 1, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    virtual_machine_maintenance_configuration  = { code = "mc", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    virtual_machine_scale_set                  = { code = "vmss", min_length = 1, max_length = 15, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    virtual_machine_scale_set_windows          = { code = "vmss", min_length = 1, max_length = 15, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    virtual_machine_scale_set_linux            = { code = "vmss", min_length = 1, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    virtual_network                            = { code = "vnet", min_length = 2, max_length = 64, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    virtual_network_gateway                    = { code = "vgw", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    virtual_network_manager                    = { code = "vnm", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    virtual_network_peering                    = { code = "peer", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "virtual network", verified = true }
    virtual_network_subnet                     = { code = "snet", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "virtual network", verified = true }
    virtual_wan                                = { code = "vwan", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    virtual_wan_hub                            = { code = "vhub", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    vm_storage_account                         = { code = "stvm", min_length = 3, max_length = 24, lowercase = true, hyphens = false, starts_with_letter = false, scope = "global", verified = true }
    vpn_connection                             = { code = "vcn", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "VPN gateway", verified = true }
    vpn_gateway                                = { code = "vpng", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    vpn_site                                   = { code = "vst", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
    web_app                                    = { code = "app", min_length = 2, max_length = 60, lowercase = false, hyphens = true, starts_with_letter = false, scope = "Global or per domain; see note below.", verified = true }
    web_application_firewall_policy            = { code = "waf", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "resource group", verified = true }
    web_application_firewall_policy_rule_group = { code = "wafrg", min_length = 1, max_length = 80, lowercase = false, hyphens = true, starts_with_letter = false, scope = "firewall policy", verified = true }
    webpubsub                                  = { code = "wps", min_length = 1, max_length = 63, lowercase = false, hyphens = true, starts_with_letter = false, scope = "", verified = false }
  }
}
