#!/usr/bin/env python3
"""Regenerates resource_types.tf and docs/resource-types.md.

Sources, both published by Microsoft:
  - Abbreviations: Cloud Adoption Framework, resource-abbreviations.md
  - Rules: Azure Resource Manager, resource-name-rules.md

Usage: python scripts/generate_resource_types.py
Needs network access. The two pages are read from the public GitHub repos.
"""
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CAF_URL = "https://raw.githubusercontent.com/MicrosoftDocs/cloud-adoption-framework/main/docs/ready/azure-best-practices/resource-abbreviations.md"
RULES_URL = "https://raw.githubusercontent.com/MicrosoftDocs/azure-docs/main/articles/azure-resource-manager/management/resource-name-rules.md"

DEFAULT = {"min_length": 1, "max_length": 63, "lowercase": False, "hyphens": True, "starts_with_letter": False}


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as resp:
        return resp.read().decode("utf-8")


def parse_rules(text):
    rows, provider = {}, None
    for line in text.splitlines():
        m = re.match(r"^## (\S+)\s*$", line)
        if m:
            provider = m.group(1)
            continue
        if not provider or not re.match(r"^(> )?\| ", line):
            continue
        cells = [c.strip() for c in re.sub(r"^> ", "", line).strip().strip("|").split("|")]
        if len(cells) < 4 or cells[0].lower() == "entity" or set(cells[0]) <= set("-: "):
            continue
        entity, scope, length, chars = cells[:4]
        arm = f"{provider}/{entity.replace(' ', '')}".lower()
        rows.setdefault(arm, {"scope": scope, "length": length, "chars": chars})
    return rows


def parse_length(text):
    m = re.match(r"\s*(\d+)\s*-\s*(\d+)", text)
    if m:
        return int(m.group(1)), int(m.group(2))
    m = re.match(r"\s*(\d+)\b(?!-bit)", text)
    return (1, int(m.group(1))) if m else None


def parse_os_lengths(text):
    """Limits that differ by operating system, such as 1-15 (Windows) and 1-64 (Linux)."""
    found = {}
    for lo, hi, a, b in re.findall(r"(\d+)\s*-\s*(\d+)\s*(?:\((Windows|Linux)\)|for (Windows|Linux))", text):
        found[(a or b).lower()] = (int(lo), int(hi))
    return found if len(found) == 2 else {}


def parse_chars(text):
    allowed = text.split("<br>")[0]
    low = allowed.lower()
    forbidden = "".join(re.findall(r"`([^`]*)`", allowed))
    deny_list = low.startswith("can't") or low.startswith("cannot")
    hyphens = ("-" not in forbidden) if deny_list else ("hyphen" in low)
    lowercase = "lowercase" in text.lower().split("<br>")[0]
    starts_with_letter = bool(
        re.search(r"start with (a |an )?(lowercase )?letter\b(?! or (number|alphanumeric))", text, re.I)
        or re.search(r"can't start with a number", text, re.I)
    )
    return {"lowercase": lowercase, "hyphens": hyphens, "starts_with_letter": starts_with_letter}


def parse_caf(text):
    out, seen = [], set()
    for line in text.splitlines():
        m = re.match(r"^\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*$", line)
        if not m or m.group(1).startswith("--") or m.group(1) == "Resource":
            continue
        label, arm_cell, abbr_cell = m.groups()
        arm = re.search(r"`(Microsoft\.[A-Za-z0-9./]+)`", arm_cell)
        codes = re.findall(r"`([^`]+)`", abbr_cell)
        if not arm or len(codes) != 1 or not re.fullmatch(r"[a-z0-9]+", codes[0]):
            continue
        out.append({"label": label, "arm": arm.group(1), "code": codes[0]})
    return out


def make_keys(entries):
    def base(label):
        label = re.sub(r"\s*\(([A-Z0-9]{2,6})\)", "", label)
        label = re.sub(r"\s+name$", "", label, flags=re.I)
        s = label.lower().replace("&", "and")
        return re.sub(r"[^a-z0-9]+", "_", s).strip("_")

    keys = {}
    for e in entries:
        keys.setdefault(base(e["label"]), []).append(e)
    result = {}
    for key, group in keys.items():
        for i, e in enumerate(group):
            k = key if i == 0 else f"{key}_{e['code']}"
            plain = re.sub(r"^(azure|microsoft)_", "", k)
            result[k] = e
            e["alias"] = plain if plain != k else None
    used = set(result)
    for k, e in list(result.items()):
        alias = e.pop("alias")
        if alias and alias not in used:
            del result[k]
            result[alias] = e
            used.add(alias)
    return dict(sorted(result.items()))


def hcl_bool(value):
    return "true" if value else "false"


def render_terraform(catalog):
    lines = [
        "# Generated by scripts/generate_resource_types.py from Microsoft's published abbreviations and",
        "# naming rules. Regenerating overwrites this file, so to change a rule or add a type for good, use",
        "# the custom_resource_types input instead of editing here.",
        "#",
        "# code: abbreviation used in the name. min_length, max_length: characters allowed.",
        "# lowercase, hyphens, starts_with_letter: naming rules. scope: where the name must be unique.",
        "# verified: false when Microsoft publishes no rule, so the defaults are used.",
        "locals {",
        "  builtin_resource_types = {",
    ]
    for key, c in catalog.items():
        lines.append(
            f'    {key} = {{ code = "{c["code"]}", min_length = {c["min_length"]}, max_length = {c["max_length"]}, '
            f'lowercase = {hcl_bool(c["lowercase"])}, hyphens = {hcl_bool(c["hyphens"])}, '
            f'starts_with_letter = {hcl_bool(c["starts_with_letter"])}, scope = "{c["scope"]}", '
            f'verified = {hcl_bool(c["verified"])} }}'
        )
    lines += ["  }", "}", ""]
    return "\n".join(lines)


def main():
    rules = parse_rules(fetch(RULES_URL))
    entries = parse_caf(fetch(CAF_URL))
    catalog = {}
    for key, e in make_keys(entries).items():
        rule = rules.get(e["arm"].lower())
        length = parse_length(rule["length"]) if rule else None
        item = {"code": e["code"], "arm_type": e["arm"], "scope": "", "verified": False, **DEFAULT}
        if rule and length:
            item.update(parse_chars(rule["chars"]))
            item.update({"min_length": length[0], "max_length": length[1], "scope": rule["scope"], "verified": True})
        catalog[key] = item
        if rule and length:
            for os_name, (lo, hi) in parse_os_lengths(rule["length"]).items():
                catalog[f"{key}_{os_name}"] = {**item, "min_length": lo, "max_length": hi}

    (ROOT / "resource_types.tf").write_text(render_terraform(catalog), encoding="utf-8")

    lines = [
        "# Resource types",
        "",
        "Generated by `scripts/generate_resource_types.py`. Do not edit by hand.",
        "",
        "List the first column values in `resource_types`. Abbreviations come from the Cloud Adoption Framework;",
        "lengths and characters come from Microsoft's naming rules page. Rows marked *unverified* have no",
        "published rule, so the module uses the defaults (1 to 63 characters, hyphens allowed) and warns.",
        "",
        "| `resource_type` | Code | Length | Lower case | Hyphens | Must start with a letter | Unique within | ARM type |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for key, c in catalog.items():
        if c["verified"]:
            row = [f"`{key}`", f"`{c['code']}`", f"{c['min_length']}-{c['max_length']}", "yes" if c["lowercase"] else "no",
                   "yes" if c["hyphens"] else "no", "yes" if c["starts_with_letter"] else "no", c["scope"], f"`{c['arm_type']}`"]
        else:
            row = [f"`{key}`", f"`{c['code']}`", "*unverified*", "", "", "", "", f"`{c['arm_type']}`"]
        lines.append("| " + " | ".join(row) + " |")
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "resource-types.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    verified = sum(1 for c in catalog.values() if c["verified"])
    print(f"{len(catalog)} resource types, {verified} verified, {len(catalog) - verified} unverified")


if __name__ == "__main__":
    main()
